export interface Vehicle {
  id: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  price: number;
  mileage: number;
  bodyType: 'Sedan' | 'SUV' | 'Truck' | 'Coupe' | 'Convertible' | 'Van' | 'Wagon';
  transmission: 'Automatic' | 'Manual';
  fuelType: 'Gasoline' | 'Diesel' | 'Hybrid' | 'Electric';
  color: string;
  vin: string;
  stockNumber: string;
  description: string;
  features: string[];
  badge?: 'Hot Deal' | 'Low Miles' | 'New Arrival' | 'Price Drop';
  imageUrl: string;
}

export const inventory: Vehicle[] = [
  {
    id: '1',
    year: 2022,
    make: 'BMW',
    model: '5 Series',
    trim: '530i',
    price: 42500,
    mileage: 18200,
    bodyType: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Black',
    vin: 'WBA53BH04NCJ12345',
    stockNumber: 'AE-1001',
    description: 'This stunning 2022 BMW 530i is a driver\'s dream. With its powerful turbocharged engine and luxurious interior, every journey becomes an experience. The low mileage makes this an exceptional value for a nearly-new luxury sedan.',
    features: ['Heated Seats', 'Navigation System', 'Sunroof', 'Apple CarPlay', 'Parking Sensors', 'Lane Departure Warning', 'Adaptive Cruise Control', 'Premium Sound System', 'LED Headlights', 'Keyless Entry'],
    badge: 'Low Miles',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
  },
  {
    id: '2',
    year: 2021,
    make: 'Toyota',
    model: 'RAV4',
    trim: 'XLE',
    price: 28900,
    mileage: 31500,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Silver',
    vin: '2T3P1RFV5MW123456',
    stockNumber: 'AE-1002',
    description: 'The 2021 Toyota RAV4 XLE is one of the best-selling SUVs for good reason. This versatile crossover delivers outstanding reliability, excellent fuel economy, and a comfortable interior that works for families and adventurers alike.',
    features: ['Backup Camera', 'Bluetooth', 'Apple CarPlay', 'Android Auto', 'Toyota Safety Sense', 'Heated Front Seats', 'Power Liftgate', 'Alloy Wheels', 'Dual-Zone Climate Control', 'USB Ports'],
    badge: 'Hot Deal',
    imageUrl: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80',
  },
  {
    id: '3',
    year: 2020,
    make: 'Ford',
    model: 'F-150',
    trim: 'XLT',
    price: 34750,
    mileage: 45800,
    bodyType: 'Truck',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Blue',
    vin: '1FTEW1EP1LFB12345',
    stockNumber: 'AE-1003',
    description: 'America\'s best-selling truck, the 2020 Ford F-150 XLT combines workhorse capability with everyday comfort. The powerful EcoBoost engine delivers impressive towing and payload capacity while still offering a refined ride.',
    features: ['Towing Package', 'Bed Liner', 'Backup Camera', 'SYNC 3', 'Bluetooth', 'Trailer Brake Controller', 'Alloy Wheels', 'Keyless Entry', 'USB Ports', 'Sirius XM Radio'],
    imageUrl: 'https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?w=800&q=80',
  },
  {
    id: '4',
    year: 2023,
    make: 'Tesla',
    model: 'Model 3',
    trim: 'Standard Range',
    price: 38900,
    mileage: 12100,
    bodyType: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Electric',
    color: 'White',
    vin: '5YJ3E1EA9PF123456',
    stockNumber: 'AE-1004',
    description: 'Experience the future of driving with this 2023 Tesla Model 3. Nearly new with ultra-low mileage, this electric sedan offers exhilarating performance, cutting-edge technology, and zero emissions. Includes full self-driving capability hardware.',
    features: ['Autopilot', 'Full Self-Driving Hardware', '15" Touchscreen', 'Over-the-Air Updates', 'Supercharger Access', 'Glass Roof', 'Heated Seats', 'Premium Sound', 'Keyless Entry', 'Mobile App Control'],
    badge: 'New Arrival',
    imageUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',
  },
  {
    id: '5',
    year: 2019,
    make: 'Audi',
    model: 'Q5',
    trim: 'Premium Plus',
    price: 31200,
    mileage: 52300,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Gray',
    vin: 'WA1BNAFY4K2123456',
    stockNumber: 'AE-1005',
    description: 'The 2019 Audi Q5 Premium Plus blends German engineering with everyday practicality. With its quattro all-wheel drive, virtual cockpit, and premium interior materials, this SUV offers a truly elevated driving experience at a reduced price.',
    features: ['Quattro AWD', 'Virtual Cockpit', 'Bang & Olufsen Sound', 'Navigation', 'Heated Seats', 'Panoramic Sunroof', 'LED Headlights', 'Parking Assist', 'Apple CarPlay', 'Audi Pre-Sense'],
    badge: 'Price Drop',
    imageUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
  },
  {
    id: '6',
    year: 2021,
    make: 'Jeep',
    model: 'Wrangler',
    trim: 'Unlimited Sport',
    price: 39500,
    mileage: 28900,
    bodyType: 'SUV',
    transmission: 'Manual',
    fuelType: 'Gasoline',
    color: 'Red',
    vin: '1C4HJXDN2MW123456',
    stockNumber: 'AE-1006',
    description: 'The 2021 Jeep Wrangler Unlimited Sport is the ultimate adventure vehicle. With its iconic design, superior off-road capability, and removable top and doors, this Wrangler is ready for any terrain you dare to explore.',
    features: ['4x4 Off-Road System', 'Removable Doors', 'Fold-Down Windshield', 'Skid Plates', 'Tow Hooks', 'Trail Rated Badge', 'Uconnect 3', 'Backup Camera', 'Keyless Entry', 'Rock Rails'],
    imageUrl: 'https://images.unsplash.com/photo-1619362280286-f1d8c722f3e0?w=800&q=80',
  },
  {
    id: '7',
    year: 2022,
    make: 'Honda',
    model: 'Accord',
    trim: 'Sport',
    price: 24800,
    mileage: 22600,
    bodyType: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'White',
    vin: '1HGCV1F34NA123456',
    stockNumber: 'AE-1007',
    description: 'The 2022 Honda Accord Sport strikes the perfect balance between sporty driving dynamics and practical daily use. With its turbocharged engine, sport-tuned suspension, and comprehensive safety features, this Accord delivers an engaging drive.',
    features: ['Honda Sensing Suite', 'Heated Front Seats', 'Apple CarPlay', 'Android Auto', 'Sport Pedals', 'Lane Keeping Assist', 'Adaptive Cruise Control', '19" Alloy Wheels', 'Backup Camera', 'Wireless Phone Charger'],
    badge: 'Low Miles',
    imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
  },
  {
    id: '8',
    year: 2018,
    make: 'Chevrolet',
    model: 'Silverado 1500',
    trim: 'LT',
    price: 28500,
    mileage: 68200,
    bodyType: 'Truck',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Black',
    vin: '1GCVKREC3JZ123456',
    stockNumber: 'AE-1008',
    description: 'This 2018 Chevrolet Silverado 1500 LT is a capable and dependable work truck with plenty of features for comfort. The proven 5.3L V8 engine provides robust performance for all your hauling and towing needs.',
    features: ['5.3L V8 EcoTec3', 'Towing Package', 'Backup Camera', 'MyLink Radio', 'Bluetooth', 'Bed Liner', 'Z71 Off-Road Package', 'Alloy Wheels', 'Remote Start', 'StabiliTrak'],
    badge: 'Hot Deal',
    imageUrl: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80',
  },
  {
    id: '9',
    year: 2020,
    make: 'Mercedes-Benz',
    model: 'GLC',
    trim: '300',
    price: 39900,
    mileage: 38700,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Silver',
    vin: 'WDC0G4KB5LF123456',
    stockNumber: 'AE-1009',
    description: 'The 2020 Mercedes-Benz GLC 300 represents the pinnacle of luxury compact SUVs. With its elegant styling, opulent interior, and advanced technology, the GLC delivers a driving experience that is both refined and exhilarating.',
    features: ['4MATIC AWD', 'MBUX Infotainment', 'Heated Seats', 'Panoramic Sunroof', 'Burmester Sound', 'Active Brake Assist', 'Navigation', 'Ambient Lighting', 'Keyless Go', 'Power Liftgate'],
    imageUrl: 'https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800&q=80',
  },
  {
    id: '10',
    year: 2021,
    make: 'Porsche',
    model: '911',
    trim: 'Carrera',
    price: 89500,
    mileage: 11200,
    bodyType: 'Coupe',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Yellow',
    vin: 'WP0AA2A97MS123456',
    stockNumber: 'AE-1010',
    description: 'The iconic 2021 Porsche 911 Carrera is a legend in automotive history. This near-mint example boasts ultra-low mileage and represents the perfect blend of everyday usability and track-ready performance. A true collector\'s opportunity.',
    features: ['PDK Transmission', 'Sport Chrono Package', 'PASM Sport Suspension', 'Bose Surround Sound', 'Sport Exhaust', 'Navigation', 'Heated Seats', 'Lane Change Assist', 'Porsche Connect', 'Rear Wiper'],
    badge: 'Low Miles',
    imageUrl: 'https://images.unsplash.com/photo-1631295868223-63265b5e97f8?w=800&q=80',
  },
  {
    id: '11',
    year: 2019,
    make: 'Toyota',
    model: 'Camry',
    trim: 'SE',
    price: 18900,
    mileage: 58400,
    bodyType: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Blue',
    vin: '4T1B11HK3KU123456',
    stockNumber: 'AE-1011',
    description: 'The 2019 Toyota Camry SE offers sporty styling and Toyota\'s legendary reliability at an accessible price point. With its responsive engine, comfortable cabin, and comprehensive safety features, the Camry SE is an excellent everyday vehicle.',
    features: ['Toyota Safety Sense 2.0', 'Apple CarPlay', 'Android Auto', 'Backup Camera', 'Sport Suspension', 'Dual Exhaust', '18" Alloy Wheels', 'Keyless Entry', 'Push Button Start', 'Adaptive Cruise Control'],
    imageUrl: 'https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=800&q=80',
  },
  {
    id: '12',
    year: 2022,
    make: 'Ford',
    model: 'Mustang',
    trim: 'GT',
    price: 42000,
    mileage: 15800,
    bodyType: 'Coupe',
    transmission: 'Manual',
    fuelType: 'Gasoline',
    color: 'Red',
    vin: '1FA6P8CF9N5123456',
    stockNumber: 'AE-1012',
    description: 'Feel the power of the 2022 Ford Mustang GT. With its legendary 5.0L Coyote V8 engine producing 460 horsepower and a proper 6-speed manual transmission, this pony car delivers an authentic, visceral driving experience that is truly unforgettable.',
    features: ['5.0L V8 460HP', '6-Speed Manual', 'Brembo Brakes', 'Active Exhaust', 'SYNC 4', 'B&O Sound System', 'Recaro Seats', 'Launch Control', 'Track Apps', 'LED Lighting'],
    badge: 'New Arrival',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
  },
  {
    id: '13',
    year: 2020,
    make: 'Chevrolet',
    model: 'Equinox',
    trim: 'LT',
    price: 22500,
    mileage: 41200,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Gray',
    vin: '2GNAXKEV5L6123456',
    stockNumber: 'AE-1013',
    description: 'The 2020 Chevrolet Equinox LT is a practical and fuel-efficient compact SUV perfect for families. With its comfortable seating, generous cargo space, and suite of safety features, the Equinox delivers great value in the crowded crossover segment.',
    features: ['MyLink 8" Display', 'Apple CarPlay', 'Android Auto', 'Backup Camera', 'Heated Front Seats', 'Power Driver Seat', 'Teen Driver Technology', 'WiFi Hotspot', 'Keyless Entry', 'Remote Start'],
    imageUrl: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80',
  },
  {
    id: '14',
    year: 2021,
    make: 'BMW',
    model: 'X5',
    trim: 'xDrive40i',
    price: 58900,
    mileage: 24500,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Black',
    vin: '5UXCR6C09M9E12345',
    stockNumber: 'AE-1014',
    description: 'The 2021 BMW X5 xDrive40i is the ultimate family SUV. Combining commanding road presence with sporting DNA, this luxurious SUV offers third-row seating, a powerful turbocharged inline-six engine, and BMW\'s legendary xDrive all-wheel drive system.',
    features: ['xDrive AWD', 'Panoramic Sky Lounge', 'Harman Kardon Sound', 'Gesture Control', 'Heated/Ventilated Seats', '5-Zone Climate', 'Parking Assist Plus', 'Night Vision', 'Head-Up Display', 'Driving Assist Pro'],
    badge: 'Low Miles',
    imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80',
  },
  {
    id: '15',
    year: 2019,
    make: 'Honda',
    model: 'CR-V',
    trim: 'EX',
    price: 23400,
    mileage: 47800,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Silver',
    vin: '2HKRW2H54KH123456',
    stockNumber: 'AE-1015',
    description: 'The 2019 Honda CR-V EX is one of the most practical and reliable compact SUVs on the market. With its spacious interior, excellent fuel economy, and comprehensive Honda Sensing safety suite, the CR-V EX excels as a family-friendly daily driver.',
    features: ['Honda Sensing', 'Sunroof', 'Heated Front Seats', 'Apple CarPlay', 'Android Auto', 'Power Liftgate', 'Rear Privacy Glass', 'LED Headlights', 'Wireless Phone Charger', 'Multi-Angle Backup Camera'],
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
  },
  {
    id: '16',
    year: 2022,
    make: 'Toyota',
    model: 'Tundra',
    trim: 'TRD Pro',
    price: 52800,
    mileage: 18900,
    bodyType: 'Truck',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'White',
    vin: '5TFLA5AB5NX123456',
    stockNumber: 'AE-1016',
    description: 'The 2022 Toyota Tundra TRD Pro is the pinnacle of off-road truck capability. Featuring a twin-turbocharged V6 engine, Fox shocks, and TRD-tuned off-road hardware, this Tundra is as comfortable blasting through trails as it is towing on the highway.',
    features: ['TRD Fox Shocks', 'Multi-Terrain Select', 'Crawl Control', 'Tow Package', 'JBL Audio', 'Heated/Ventilated Seats', '14" Touchscreen', 'Bird\'s Eye View Camera', 'Tonneau Cover', 'Rock Rails'],
    badge: 'New Arrival',
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&q=80',
  },
  {
    id: '17',
    year: 2020,
    make: 'Audi',
    model: 'A4',
    trim: 'Premium',
    price: 32500,
    mileage: 35600,
    bodyType: 'Sedan',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Gray',
    vin: 'WAUENAF46LA123456',
    stockNumber: 'AE-1017',
    description: 'The 2020 Audi A4 Premium is a masterpiece of German engineering. With its sleek styling, turbocharged engine, and Audi\'s renowned build quality, this executive sedan delivers a driving experience that effortlessly blends performance and refinement.',
    features: ['quattro AWD', 'Virtual Cockpit', 'MMI Navigation', 'Bang & Olufsen Sound', 'Heated Seats', 'Audi Pre Sense', 'Lane Departure Warning', 'Rear Cross Traffic Alert', 'Power Sunroof', 'LED Matrix Headlights'],
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
  },
  {
    id: '18',
    year: 2021,
    make: 'Jeep',
    model: 'Grand Cherokee',
    trim: 'Laredo',
    price: 35900,
    mileage: 31200,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Blue',
    vin: '1C4RJFAG0MC123456',
    stockNumber: 'AE-1018',
    description: 'The 2021 Jeep Grand Cherokee Laredo combines rugged capability with upscale comfort. With its Selec-Terrain traction control system, luxurious interior appointments, and iconic Jeep styling, the Grand Cherokee is the definitive American SUV.',
    features: ['Selec-Terrain', 'Uconnect 8.4', 'Navigation', 'Backup Camera', 'Heated Front Seats', 'Blind Spot Monitoring', 'Rear Park Assist', 'Remote Start', 'Power Liftgate', 'Keyless Enter-N-Go'],
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
  },
  {
    id: '19',
    year: 2018,
    make: 'Ford',
    model: 'Explorer',
    trim: 'XLT',
    price: 24750,
    mileage: 72100,
    bodyType: 'SUV',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Black',
    vin: '1FM5K8D86JGA12345',
    stockNumber: 'AE-1019',
    description: 'The 2018 Ford Explorer XLT is a capable three-row family SUV offering generous passenger and cargo space. With its SYNC 3 infotainment system, comprehensive safety features, and available all-wheel drive, the Explorer handles whatever family life throws at it.',
    features: ['3-Row Seating', 'SYNC 3', 'Navigation', 'Backup Camera', 'Heated Front Seats', 'Dual-Zone Climate', 'Power Liftgate', 'Trailer Tow Package', 'Blind Spot Monitoring', 'MyKey'],
    badge: 'Price Drop',
    imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80',
  },
  {
    id: '20',
    year: 2022,
    make: 'Chevrolet',
    model: 'Corvette',
    trim: 'Stingray',
    price: 65000,
    mileage: 8900,
    bodyType: 'Coupe',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    color: 'Red',
    vin: '1G1YB3D45N5123456',
    stockNumber: 'AE-1020',
    description: 'The mid-engine 2022 Chevrolet Corvette Stingray is an American icon reimagined. With its naturally aspirated 6.2L V8 producing 495 horsepower, mid-engine layout, and stunning styling, this Corvette offers exotic car performance and thrills at a fraction of the price.',
    features: ['6.2L LT2 V8 495HP', 'Mid-Engine Layout', 'Magnetic Ride Control', 'Bose Performance Audio', 'Head-Up Display', 'Performance Data Recorder', 'Front Lift System', 'Carbon Flash Badges', 'GT2 Seats', 'Launch Control'],
    badge: 'Low Miles',
    imageUrl: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=800&q=80',
  },
];
